# Readme



### 函数定义

In [ ]:
import numpy as np
# 考虑到测试中只有一个channel,所以batchN 和 channel默认为1～所以次卷积只用于n =1,c =1
def conv2d(x,w = None, stride=2, padding=0):
    """
    2D卷积层
    :x: 输入数据，形状为 ( C, H, W) 单张图片默认N= 0
    :w: 卷积核，形状为 (C_out, C_in, H_k, W_k)
    :b: 偏置项，形状为 (C_out,)
    :stride: 步长
    :padding: 填充
    :return: 输出数据，形状为 ( C_out, H_out, W_out)
    """
    if w is None:
        w = np.array([[1, 0, 2],
            [ 0, 1, 0],
            [ 1, 0, 1]])
    print(x.shape)
    H, W = x.shape#读取输入的channel,和尺寸
    H_k, W_k = w.shape#读取卷积核的channel,和尺寸
    C_out=1
    C_in=1
    H_out = (H - H_k + 2 * padding) // stride + 1#计算卷积后的高宽
    W_out = (W - W_k + 2 * padding) // stride + 1
    #x_padded = np.pad(x, ((padding, padding), (padding, padding)), mode='constant')#填充
    x_padded = x
    print(x_padded)
    out = np.zeros(( C_out, H_out, W_out))
    for c_out in range(C_out):
        for i in range(H_out):
            for j in range(W_out):
                print(x_padded[i*stride:i*stride+H_k, j*stride:j*stride+W_k])
                print(w)
                out[c_out, i, j] = np.sum(x_padded[i*stride:i*stride+H_k, j*stride:j*stride+W_k] * w)
    return out

def pooling(x,pool_type='max',pool_size=2,stride=2):
    """
    池化层
    :x: 输入数据，形状为 (C, H, W)
    :pool_type: 池化类型，'max'或'avg'
    :pool_size: 池化窗口大小
    :stride: 步长
    :return: 输出数据，形状为 (C, H_out, W_out)
    """
    print(x.shape)
    c ,H, W = x.shape
    H_out = (H - pool_size) // stride + 1#计算池化后的高宽
    W_out = (W - pool_size) // stride + 1
    # x_padded = np.pad(x, ((padding, padding), (padding, padding)), mode='constant')
    # c =1 
    out = np.zeros((c,H_out, W_out))
    for c_ in range(c):
        for i in range(H_out):
            for j in range(W_out):
                if pool_type == 'max':
                    out[0, i, j] = np.max(x[0, i*stride:i*stride+pool_size, j*stride:j*stride+pool_size])
                elif pool_type == 'avg':
                    out[0, i, j] = np.mean(x[0, i*stride:i*stride+pool_size, j*stride:j*stride+pool_size])
    return out


### 测试卷积

In [ ]:
import numpy as np
import re

# 输入矩阵总行数和总列数
while True:
    try:
        rows, cols = map(int, input().split())
        
        if rows > 0 and cols > 0:
            break
        print("InputError please input integers fo col and row")
    except ValueError:
        print("ERROR")

input_str = input().strip()# 输入矩阵元素
cleaned = re.sub(r'[\[\]]', ' ', input_str)#移除[]
# 分割为数字字符串列表
num_strings = [s for s in cleaned.split() if s]
# 转换为整数
numbers = list(map(int, num_strings))

if len(numbers) != rows * cols:
    print("ERROR")
else:
    # 转换为NumPy数组
    arr = np.array(numbers).reshape(rows, cols)
    print(arr)
    
conved_arr = conv2d(arr)
print(conved_arr)
print(pooling(conved_arr))


[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [ 6  5  4  3  2]
 [ 1  2  3  4  5]
 [12 11 10  9  8]]
(5, 5)
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [ 6  5  4  3  2]
 [ 1  2  3  4  5]
 [12 11 10  9  8]]
[[1 2 3]
 [7 8 9]
 [6 5 4]]
[[1 0 2]
 [0 1 0]
 [1 0 1]]
[[ 3  4  5]
 [ 9 10 11]
 [ 4  3  2]]
[[1 0 2]
 [0 1 0]
 [1 0 1]]
[[ 6  5  4]
 [ 1  2  3]
 [12 11 10]]
[[1 0 2]
 [0 1 0]
 [1 0 1]]
[[ 4  3  2]
 [ 3  4  5]
 [10  9  8]]
[[1 0 2]
 [0 1 0]
 [1 0 1]]
[[[25. 29.]
  [38. 30.]]]
(1, 2, 2)
[[[38.]]]


## 梯度提升证明题

![man!](math.jpg)